export const destinationPages = [
    [
      {
        id: 1,
        image: "/img2.avif",
        category: "Trekking",
        title: "Top 10 places",
        slug: "Top-10-places",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
      {
        id: 2,
        image: "/img3.avif",
        category: "Sightseeing",
        title: "Cultural Heritage",
        slug: "Cultural-Heritage",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
      {
        id: 3,
        image: "/mount.jpg",
        category: "Adventures",
        title: "River Rafting",
        slug: "River-Rafting",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
      {
        id: 4,
        image: "/rara.avif",
        category: "Adventures",
        title: "Green Fields of Nepal",
        slug: "Green-Fields-of-Nepal",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
    ],
    [
        {
          id: 5,
          image: "/mount.jpg",
          category: "Extreme",
          title: "Bungee Jumping",
          slug: "Bungee-Jumping",
          date: "20 Jan, 2025",
          readTime: "5mins read",
        },
        {
          id: 6,
          image: "/rara.avif",
          category: "Nature",
          title: "Wildlife Safari",
          slug: "Wildlife-Safari",
          date: "22 Jan, 2025",
          readTime: "15mins read",
        },
        {
          id: 7,
          image: "/img2.avif",
          category: "Hiking",
          title: "Mountain Trails",
          slug: "Mountain-Trails",
          date: "15 Jan, 2025",
          readTime: "10mins read",
        },
        {
          id: 8,
          image: "/img3.avif",
          category: "Cultural",
          title: "Temple Tours",
          slug: "Temple-Tours",
          date: "18 Jan, 2025",
          readTime: "8mins read",
        },
      ],
    [
      {
        id: 9,
        image: "/img2.avif",
        category: "Trekking",
        title: "Top 10 places",
        slug: "Top-10-places",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
      {
        id: 10,
        image: "/img3.avif",
        category: "Sightseeing",
        title: "Cultural Heritage",
        slug: "Cultural-Heritage",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
      {
        id: 11,
        image: "/mount.jpg",
        category: "Adventures",
        title: "River Rafting",
        slug: "River-Rafting",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
      {
        id: 12,
        image: "/rara.avif",
        category: "Adventures",
        title: "Green Fields of Nepal",
        slug: "Green-Fields-of-Nepal",
        date: "12 Jan, 2025",
        readTime: "12mins read",
      },
    ],
    [
      {
        id: 13,
        image: "/img2.avif",
        category: "Hiking",
        title: "Mountain Trails",
        slug: "Mountain-Trails",
        date: "15 Jan, 2025",
        readTime: "10mins read",
      },
      {
        id: 14,
        image: "/img3.avif",
        category: "Cultural",
        title: "Temple Tours",
        slug: "Temple-Tours",
        date: "18 Jan, 2025",
        readTime: "8mins read",
      },
      {
        id: 15,
        image: "/mount.jpg",
        category: "Extreme",
        title: "Bungee Jumping",
        slug: "Bungee-Jumping",
        date: "20 Jan, 2025",
        readTime: "5mins read",
      },
      {
        id: 16,
        image: "/rara.avif",
        category: "Nature",
        title: "Wildlife Safari",
        slug: "Wildlife-Safari",
        date: "22 Jan, 2025",
        readTime: "15mins read",
      },
    ],
   
  ];